## https://github.com/localstack/helm-charts/blob/main/charts/localstack/values.yaml
ingress:
  enabled: true
  hosts:
  - host: localstack.${domain-name}
    paths:
    - path: /
      pathType: Prefix
  tls:
  - secretName: localstack-cert
    hosts:
     - localstack.${domain-name}

service:
  type: ClusterIP