apiVersion: ydb.tech/v1alpha1
kind: Database
metadata:
  name: database-sample
  namespace: ${namespace}
spec:
  image:
    name: cr.yandex/crptqonuodf51kdj7a7d/ydb:23.3.17
  nodes: 1
  domain: Root
  service:
    grpc:
      externalHost: localhost
  resources:
    storageUnits:
      - count: 1
        unitKind: ssd
  storageClusterRef:
    name: storage-sample
---

apiVersion: ydb.tech/v1alpha1
kind: DatabaseMonitoring
metadata:
  name: database-sample
  namespace: ${namespace}
  labels:
    release: prom
spec:
  databaseRef:
    name: database-sample